.austriancoder-etnaviv-rules:
  stage: etnaviv
  rules:
    - !reference [.austriancoder-farm-rules, rules]
    - !reference [.gl-rules, rules]
    - changes: &etnaviv_file_list
      - src/etnaviv/**/*
      - src/gallium/drivers/etnaviv/**/*
      - src/gallium/winsys/etnaviv/**/*
      - src/gallium/auxiliary/renderonly/**/*
      - src/gallium/winsys/kmsro/**/*
      when: on_success

.austriancoder-etnaviv-manual-rules:
  stage: etnaviv
  retry: !reference [.scheduled_pipeline-rules, retry]
  rules:
    - !reference [.austriancoder-farm-manual-rules, rules]
    - !reference [.gl-manual-rules, rules]
    - changes:
        *etnaviv_file_list
      when: manual

.heidelberg-etnaviv-rules:
  stage: etnaviv
  rules:
    - !reference [.heidelberg-farm-rules, rules]
    - !reference [.gl-rules, rules]
    - changes: &etnaviv_file_list
      - src/etnaviv/**/*
      - src/gallium/drivers/etnaviv/**/*
      - src/gallium/winsys/etnaviv/**/*
      - src/gallium/auxiliary/renderonly/**/*
      - src/gallium/winsys/kmsro/**/*
      when: on_success

.heidelberg-etnaviv-manual-rules:
  stage: etnaviv
  retry: !reference [.scheduled_pipeline-rules, retry]
  rules:
    - !reference [.heidelberg-farm-manual-rules, rules]
    - !reference [.gl-manual-rules, rules]
    - changes:
        *etnaviv_file_list
      when: manual

.austriancoder-etnaviv-test:
  extends:
    - .austriancoder-etnaviv-rules
  script:
    - ./install/bare-metal/fastboot.sh
  variables:
    BM_CMDLINE: "ip=dhcp console=ttymxc0,115200n8 root=/dev/nfs rw nfsrootdebug init=/init $BM_KERNELARGS"
    FLAKES_CHANNEL: "#etnaviv-ci"

# 32-bit
.etnaviv-gc2000:arm32:
  variables:
    DEQP_EXPECTED_RENDERER: GC2000
    GPU_VERSION: "etnaviv-gc2000"

.austriancoder:imx6q-cubox-i:arm32:
  extends:
    - .baremetal-test-arm32
    - .austriancoder-etnaviv-test
    - .etnaviv-gc2000:arm32
  variables:
    BM_KERNEL: zImage
    BM_DTB: imx6q-cubox-i
  tags:
    - etnaviv-gc2000

gc2000_gles2:
  extends:
    - .austriancoder:imx6q-cubox-i:arm32
    - .austriancoder-etnaviv-manual-rules
  variables:
    HWCI_TEST_SCRIPT: "/install/deqp-runner.sh"
    DEQP_VER: gles2

gc2000_gles2_asan:
  extends:
    - gc2000_gles2
    - .baremetal-arm32-asan-test
  variables:
    DEQP_FRACTION: 100
    FDO_CI_CONCURRENT: 1

gc2000_piglit:
  extends:
    - .piglit-test
    - .austriancoder:imx6q-cubox-i:arm32
    - .austriancoder-etnaviv-manual-rules
  variables:
    PIGLIT_PLATFORM: gbm
    PIGLIT_PROFILES: gpu
    TEST_PHASE_TIMEOUT: 40

# 64-bit
.etnaviv-gc7000:arm64:
  variables:
    DEQP_EXPECTED_RENDERER: GC7000
    GPU_VERSION: "etnaviv-gc7000"

.austriancoder:imx8mq-nitrogen:arm64:
  extends:
    - .baremetal-test-arm64
    - .austriancoder-etnaviv-test
    - .etnaviv-gc7000:arm64
  variables:
    BM_DTB: imx8mq-nitrogen
    BM_KERNEL: Image
  tags:
    - austriancoder-etnaviv-imx8mq-nitrogen

gc7000_gles2:
  extends:
    - .austriancoder:imx8mq-nitrogen:arm64
    - .austriancoder-etnaviv-manual-rules
  variables:
    HWCI_TEST_SCRIPT: "/install/deqp-runner.sh"
    DEQP_VER: gles2

# 2 devices (2023-07-25)
.heidelberg:imx8mq-librem5-devkit:arm64:
  extends:
    - .labgrid-test:arm64
    - .etnaviv-gc7000:arm64
    - .heidelberg-etnaviv-rules
  tags:
    - heidelberg:imx8mq-librem5-devkit

gc7000-gles2:arm64:
  extends:
    - .heidelberg:imx8mq-librem5-devkit:arm64
  variables:
    HWCI_TEST_SCRIPT: "/install/deqp-runner.sh"
    DEQP_VER: gles2

# not stable yet, multiple traces randomly flaking
gc7000-traces:arm64:
  extends:
    - .heidelberg:imx8mq-librem5-devkit:arm64
    - .heidelberg-etnaviv-manual-rules
  variables:
    HWCI_TEST_SCRIPT: "/install/piglit/piglit-traces.sh"
    HWCI_START_WESTON: 1
    PIGLIT_PLATFORM: mixed_glx_egl
    PIGLIT_REPLAY_DESCRIPTION_FILE: "/install/traces-etnaviv.yml"
    PIGLIT_REPLAY_DEVICE_NAME: $GPU_VERSION
