.etnaviv-rules:
  stage: etnaviv
  rules:
    - !reference [.austriancoder-farm-rules, rules]
    - !reference [.gl-rules, rules]
    - changes: &etnaviv_file_list
      - src/etnaviv/**/*
      - src/gallium/drivers/etnaviv/**/*
      - src/gallium/winsys/etnaviv/**/*
      - src/gallium/auxiliary/renderonly/**/*
      - src/gallium/winsys/kmsro/**/*
      when: on_success

.etnaviv-manual-rules:
  stage: etnaviv
  retry: !reference [.scheduled_pipeline-rules, retry]
  rules:
    - !reference [.austriancoder-farm-manual-rules, rules]
    - !reference [.gl-manual-rules, rules]
    - changes:
        *etnaviv_file_list
      when: manual

gc2000_gles2:
  extends:
    - .baremetal-test-arm32
    - .austriancoder-imx6q-cubox-i:arm32
    - .etnaviv-manual-rules
  variables:
    FLAKES_CHANNEL: "#etnaviv-ci"
    HWCI_TEST_SCRIPT: "/install/deqp-runner.sh"
    DEQP_VER: gles2

gc2000_gles2_asan:
  extends:
    - gc2000_gles2
    - .baremetal-arm32-asan-test
  variables:
    DEQP_FRACTION: 100
    FDO_CI_CONCURRENT: 1

gc2000_piglit:
  extends:
    - .piglit-test
    - .baremetal-test-arm32
    - .austriancoder-imx6q-cubox-i:arm32
    - .etnaviv-manual-rules
  variables:
    FLAKES_CHANNEL: "#etnaviv-ci"
    PIGLIT_PLATFORM: gbm
    PIGLIT_PROFILES: gpu
    TEST_PHASE_TIMEOUT: 40

gc7000_gles2:
  extends:
    - .baremetal-test-arm64
    - .austriancoder-imx8mq-nitrogen:arm64
    - .etnaviv-manual-rules
  variables:
    FLAKES_CHANNEL: "#etnaviv-ci"
    HWCI_TEST_SCRIPT: "/install/deqp-runner.sh"
    DEQP_VER: gles2
