.nouveau-rules:
  stage: nouveau
  rules:
    - !reference [.anholt-farm-rules, rules]
    - !reference [.gl-rules, rules]
    - changes: &nouveau_file_list
      - src/nouveau/**/*
      - src/gallium/drivers/nouveau/**/*
      - src/gallium/winsys/kmsro/**/*
      - src/gallium/winsys/nouveau/**/*
      when: on_success

.nouveau-manual-rules:
  stage: nouveau
  retry: !reference [.scheduled_pipeline-rules, retry]
  rules:
    - !reference [.anholt-farm-manual-rules, rules]
    - !reference [.gl-manual-rules, rules]
    - changes:
        *nouveau_file_list
      when: manual


# General settings for bare-metal nouveau testing on either arm64 or arm32.
.nouveau-bm-test:
  extends:
    - .nouveau-rules
  variables:
    FLAKES_CHANNEL: "#nouveau-ci"

gk20a-gles:
  extends:
    - .baremetal-test-arm32
    - .nouveau-bm-test
    - .anholt-tegra124-jetson-tk1:arm32
  parallel: 4
  timeout: 30m
  variables:
    HWCI_TEST_SCRIPT: "/install/deqp-runner.sh"
    DEQP_SUITE: nouveau-gk20a

.gm20b-gles-full:
  extends:
    - .baremetal-test-arm64
    - .nouveau-bm-test
    - .google-tegra210-p3450-0000:arm64
    - .nouveau-manual-rules
  timeout: 2h
  variables:
    HWCI_TEST_SCRIPT: "/install/deqp-runner.sh"
    DEQP_SUITE: nouveau-gm20b
    TEST_PHASE_TIMEOUT: 120

.gm20b-gles:
  extends:
    - .gm20b-gles-full
  timeout: 30m
  variables:
    DEQP_FRACTION: 10
